/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiSelect: typeof import('./src/components/api-select/src/ApiSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EllipsisText: typeof import('./src/components/ellipsis-text/src/EllipsisText.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Pagination: typeof import('./src/components/schema-table/src/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./src/components/schema-from/src/SchemaForm.vue')['default']
    SchemaFormItem: typeof import('./src/components/schema-from/src/SchemaFormItem.vue')['default']
    SchemaFromItem: typeof import('./src/components/schema-from/src/SchemaFormItem.vue')['default']
    SchemaTable: typeof import('./src/components/schema-table/src/SchemaTable.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/src/SvgIcon.vue')['default']
    TableColumn: typeof import('./src/components/schema-table/src/TableColumn.vue')['default']
    TcPagination: typeof import('./src/components/schema-table/src/TcPagination.vue')['default']
    Tooltip: typeof import('./src/components/ellipsis-text/src/Tooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
